#!/bin/sh

if [ -d "$HOME/bin" ]; then
    export PATH="$PATH:$HOME/bin"
fi
export EDITOR=vim

eval `dircolors $HOME/.config/dir_colors`

source_if_possible() {
    if [ -f $@ ] && [ -r $@ ]; then
        source $@
    fi
}
