#!/bin/sh

#$HOME/bin isn't necessarily in $PATH yet.
source "$($HOME/bin/xdg_config_home)/shells/environment"

#uim-fep will launch $SHELL _again_, so this should run before starting any other services.
if is_shell_interactive; then
    if [ -z "$DISPLAY" ] && [ "$TERM" = "linux" ]; then
        if [ -z "$UIM_FEP_PID" ]; then
            #Note: -l is not defined by POSIX
            exec uim-fep -e "$SHELL" "-l"
        fi
        make_linux_console_solarized_dark
    fi
fi

