#!/bin/sh

export PATH=/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.5.3:/usr/games/bin:/$HOME/bin

check_program () {
    for program
    do
        command -v "$program" > /dev/null && return
    done
    app=
}

check_program vifm mc;																   export TERMINAL_FILE_MANAGER=$program
check_program links w3m;															   export TERMINAL_WEB_BROWSER=$program
check_program vim vi nano;															   export TERMINAL_EDITOR=$program
check_program mutt;																   export TERMINAL_EMAIL_READER=$program
check_program newsbeuter;															   export TERMINAL_FEED_READER=$program
check_program mocp cmus mplayer;														   export TERMINAL_AUDIO_PLAYER=$program
check_program mplayer;																   export TERMINAL_VIDEO_PLAYER=$program
check_program weechat-curses irsii ii bitchx;													   export TERMINAL_IRC_CLIENT=$program
check_program weechat-curses;															   export TERMINAL_CHAT_CLIENT=$program
check_program rtorrent;																   export TERMINAL_TORRENT_DOWNLOADER=$program
check_program sc;																   export TERMINAL_SPREADSHEET=$program
check_program htop top;																   export TERMINAL_PROCESS_MANAGER=$program
check_program conky;																   export TERMINAL_SYSTEM_MONITOR=$program
check_program less more pg;															   export TERMINAL_PAGER=$program

check_program urxvtc termite xterm terminator;     												   export GRAPHICAL_TERMINAL_EMULATOR=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_FILE_MANAGER\""; 									   export GRAPHICAL_FILE_MANAGER=$program
check_program firefox uzbl vimperator; 		   												   export GRAPHICAL_WEB_BROWSWER=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_EDITOR\"" gvim; 									   export GRAPHICAL_EDITOR=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_EMAIL_READER\"" thunderbird; 							   export GRAPHICAL_EMAIL_READER=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_FEED_READER\"" liferea thunderbird; 							   export GRAPHICAL_FEED_READER=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_AUDIO_PLAYER\""; 									   export GRAPHICAL_AUDIO_PLAYER=$program
check_program mplayer vlc; 			  												   export GRAPHICAL_VIDEO_PLAYER=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_IRC_CLIENT\"" xchat; 								   export GRAPHICAL_IRC_CLIENT=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_CHAT_CLIENT\""; 									   export GRAPHICAL_CHAT_CLIENT=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_TORRENT_DOWNLOADER\"" transmission; 							   export GRAPHICAL_TORRENT_DOWNLOADER=$program
check_program abiword; 				  												   export GRAPHICAL_WORD_PROCESSOR=$program
check_program gnumeric; 			  												   export GRAPHICAL_SPREADSHEET=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_PROCESS_MANAGER\""; 									   export GRAPHICAL_PROCESS_MANAGER=$program
check_program conky; 				  												   export GRAPHICAL_SYSTEM_MONITOR=$program
check_program "$GRAPHICAL_TERMINAL_EMULATOR -e \"$TERMINAL_PAGER\""; 										   export GRAPHICAL_PAGER=$program

if [ -n $DISPLAY ]; then
	export FILE_MANAGER=$GRAPHICAL_FILE_MANAGER
	export WEB_BROWSER=$GRAPHICAL_WEB_BROWSWER
	export EMAIL_READER=$GRAPHICAL_EMAIL_READER
	export FEED_READER=$GRAPHICAL_FEED_READER
	export AUDIO_PLAYER=$GRAPHICAL_AUDIO_PLAYER
	export VIDEO_PLAYER=$GRAPHICAL_VIDEO_PLAYER
	export IRC_CLIENT=$GRAPHICAL_IRC_CLIENT
	export CHAT_CLIENT=$GRAPHICAL_CHAT_CLIENT
	export TORRENT_DOWNLOADER=$GRAPHICAL_TORRENT_DOWNLOADER
	export WORD_PROCESSOR=$GRAPHICAL_WORD_PROCESSOR
	export SPREADSHEET=$GRAPHICAL_SPREADSHEET
	export PROCESS_MANAGER=$GRAPHICAL_PROCESS_MANAGER
	export SYSTEM_MONITOR=$GRAPHICAL_SYSTEM_MONITOR
	export EDITOR=$GRAPHICAL_EDITOR
	#export PAGER="/bin/sh -c \"unset PAGER;col -b -x | view -c 'set ft=man nomod nolist' -\""
	export PAGER=$GRAPHICAL_PAGER
else
	export FILE_MANAGER=$TERMINAL_FILE_MANAGER
	export WEB_BROWSER=$TERMINAL_WEB_BROWSER
	export EMAIL_READER=$TERMINAL_EMAIL_READER
	export FEED_READER=$TERMINAL_FEED_READER
	export AUDIO_PLAYER=$TERMINAL_AUDIO_PLAYER
	export VIDEO_PLAYER=$TERMINAL_VIDEO_PLAYER
	export IRC_CLIENT=$TERMINAL_IRC_CLIENT
	export CHAT_CLIENT=$TERMINAL_CHAT_CLIENT
	export TORRENT_DOWNLOADER=$TERMINAL_TORRENT_DOWNLOADER
	export SPREADSHEET=$TERMINAL_SPREADSHEET
	export PROCESS_MANAGER=$TERMINAL_PROCESS_MANAGER
	export SYSTEM_MONITOR=$TERMINAL_SYSTEM_MONITOR
	export EDITOR=$TERMINAL_EDITOR
	export PAGER=$TERMINAL_PAGER
fi
